# Generated by Django 2.2.10 on 2020-02-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20200218_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('create_business', 'update_business')]},
        ),
    ]
